"""empty message

Revision ID: 70cfd4a57ccf
Revises: 8e42cc36352a
Create Date: 2024-01-30 20:22:39.791521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70cfd4a57ccf'
down_revision: Union[str, None] = '8e42cc36352a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_owners_association')
    op.add_column('book', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'book', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'owner_id')
    op.create_table('book_owners_association',
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name='book_owners_association_book_id_fkey'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='book_owners_association_owner_id_fkey')
    )
    # ### end Alembic commands ###
