"""test running migrations

Revision ID: 8c94a3956af5
Revises: 8c5ca2ef2cb9
Create Date: 2024-03-08 17:31:03.239520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c94a3956af5'
down_revision: Union[str, None] = '8c5ca2ef2cb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
