"""empty message

Revision ID: 78c845818556
Revises: 670bd96786d1
Create Date: 2024-01-27 03:37:13.226071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78c845818556'
down_revision: Union[str, None] = '670bd96786d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('url_orig', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'rating', ['id'])
    op.drop_column('rating', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'rating', type_='unique')
    op.drop_column('rating', 'url_orig')
    # ### end Alembic commands ###
