"""empty message

Revision ID: a691bfbde9ca
Revises: f5bf002c26d8
Create Date: 2024-01-29 00:36:11.119387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a691bfbde9ca'
down_revision: Union[str, None] = 'f5bf002c26d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('saved_to_profile', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'saved_to_profile')
    # ### end Alembic commands ###
