"""empty message

Revision ID: 1412112fe076
Revises: a691bfbde9ca
Create Date: 2024-01-30 19:16:30.170536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1412112fe076'
down_revision: Union[str, None] = 'a691bfbde9ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_owners_association',
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], )
    )
    op.drop_constraint('book_owner_id_fkey', 'book', type_='foreignkey')
    op.drop_column('book', 'owner_id')
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'profile_image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index('ix_user_id', table_name='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_id', 'user', ['id'], unique=True)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'profile_image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('book', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('book_owner_id_fkey', 'book', 'user', ['owner_id'], ['id'])
    op.drop_table('book_owners_association')
    # ### end Alembic commands ###
