"""empty message

Revision ID: f5bf002c26d8
Revises: b400bf8a878e
Create Date: 2024-01-29 00:17:00.734629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5bf002c26d8'
down_revision: Union[str, None] = 'b400bf8a878e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'is_saved_to_profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('is_saved_to_profile', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
