"""empty message

Revision ID: 753e468bf65e
Revises: df03e1ee4afe
Create Date: 2024-01-31 16:32:35.183770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '753e468bf65e'
down_revision: Union[str, None] = 'df03e1ee4afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'saved_to_profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('saved_to_profile', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
