"""empty message

Revision ID: 663b2e0ca229
Revises: a439a276ef6c
Create Date: 2024-01-27 22:08:07.554818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '663b2e0ca229'
down_revision: Union[str, None] = 'a439a276ef6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('title', sa.String(), nullable=True))
    op.add_column('rating', sa.Column('image', sa.String(), nullable=True))
    op.add_column('rating', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rating', 'description')
    op.drop_column('rating', 'image')
    op.drop_column('rating', 'title')
    # ### end Alembic commands ###
