"""empty message

Revision ID: df03e1ee4afe
Revises: 70cfd4a57ccf
Create Date: 2024-01-31 16:31:50.630475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df03e1ee4afe'
down_revision: Union[str, None] = '70cfd4a57ccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('is_saved_to_profile', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'book_id')
    )
    op.drop_table('rating')
    op.drop_constraint('book_owner_id_fkey', 'book', type_='foreignkey')
    op.drop_column('book', 'owner_id')
    op.drop_column('book', 'user_rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('user_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('book', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('book_owner_id_fkey', 'book', 'user', ['owner_id'], ['id'])
    op.create_table('rating',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url_orig', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='rating_pkey'),
    sa.UniqueConstraint('id', name='rating_id_key')
    )
    op.drop_table('library')
    # ### end Alembic commands ###
