"""test running migrations

Revision ID: dfb88d2f2e4b
Revises: b04b1b8532f1
Create Date: 2024-02-28 15:29:59.012330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfb88d2f2e4b'
down_revision: Union[str, None] = 'b04b1b8532f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
