"""empty message

Revision ID: def7748d0f2c
Revises: 663b2e0ca229
Create Date: 2024-01-28 00:29:41.684104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'def7748d0f2c'
down_revision: Union[str, None] = '663b2e0ca229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rating', 'url')
    # ### end Alembic commands ###
