"""test running migrations

Revision ID: 018a6284c9cb
Revises: 9f1fe3ebc8d7
Create Date: 2024-03-07 22:21:14.923659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '018a6284c9cb'
down_revision: Union[str, None] = '9f1fe3ebc8d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
